### ISSUE TITLE
TypeError: solidAuthClient.trackSession is not a function

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-logic#20]
It seems there were breaking changes between solid-logic v1.2.9 and latest.
For instance, when I try to update the monetization-tests to use the latest version of solid-logic, I get an error:

```sh
 TypeError: solidAuthClient.trackSession is not a function

      10 | 
      11 |   constructor(solidAuthClient: SolidAuthClient) {
    > 12 |     solidAuthClient.trackSession((session) => {
         |                     ^
      13 |       this.session = session;
      14 |     });
      15 |   }

      at new SolidAuthClientAuthnLogic (../solid-logic/src/authn/SolidAuthClientAuthnLogic.ts:12:21)
      at new SolidLogic (../solid-logic/src/index.ts:62:20)
      at Object.<anonymous> (test/helpers/env.ts:21:10)
      at step (test/helpers/env.ts:33:23)
      at Object.next (test/helpers/env.ts:14:53)
      at fulfilled (test/helpers/env.ts:5:58)
```

@angelo-v is there an easy work-around for this, do you know?

**Comment by angelo-v** [comment]
How are you instantiating SolidLogic? You need to either pass a valid instance of solid-auth-client as second parameter, or leave it out, if you do not need logic that relies on auth

**Comment by michielbdejong** [comment]
i'm passing a solid-auth-fetcher instance as the first parameter and a webId as the second:
https://github.com/solid/web-access-control-tests/blob/main/test/helpers/env.ts#L21
This works with v1.2.9, but not with v1.3.1, so looks like we broke semver?

**Comment by michielbdejong** [comment]
The 'me' parameter was removed in https://github.com/solid/solid-logic/commit/07d0a9a4dc781bcafa6e4052c3a88f9c4dbda1ef#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L25

**Comment by michielbdejong** [comment]
We went from
` constructor (fetcher: { fetch: () => any }, me?: string)`
to
`constructor(fetcher: { fetch: () => any }, solidAuthClient)`
there.

I think I can work around it, I'll just add the `me` back as a third, optional parameter.

**Comment by angelo-v** [comment]
Oh yes, indeed, I removed the me, because it appeared unused to me (it was just passed and never accessed and also not passed from solid-ui). I guess this impression was wrong then, I am sorry!

So what is your use case for passing `me`? It feels contradictory to pass both a fixed `me` value and an auth client. And I still don't get where the `me` is / was used.

**Comment by michielbdejong** [comment]
yes, true, it's cleaner if the auth client provides the value of 'me'. I was using it for instance [here](https://github.com/solid/web-access-control-tests/blob/main/test/surface/acl-doc-application.test.ts#L54) but I can easily use `WEBID_ALICE` instead of `solidLogicAlice.me` there.
